config/routes.rb
Rails.application.routes.draw do
  root to: "boards#index" 
  resources :sdates
  resources :boards
  resources :rooms, only: [:new, :create, :destroy] do
    resources :messages, only: [:index, :create, :destroy]
    # member do
    #   post '/', to: 'rooms#add', as: 'add'
    #   get '/messages/', to: 'messages#index', as: 'message'
    # end
  end
  resources :adminrooms, only: [:new, :create, :destroy] do
    resources :adminmessages, only: [:index, :create, :destroy]
  # get 'rooms/:target_id', to: 'rooms#new', as: 'new_room' 
  # get 'rooms/:target_id/messages/', to 'messages#index'
  end

  resources :schedules do
    resources :checks, only: [:create,:update]
    member do
      get 'preview'
      post '/users/:user_id', to: 'confirms#switch'
      patch '/users/:user_id', to: 'confirms#switch'
      get 'next_preview'
      post '/next_users/:user_id', to: 'confirms#next_switch'
      patch '/next_users/:user_id', to: 'confirms#next_switch'
    end
  end

  resources :nextschedules
  resources :confirmedschedules
 
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  get 'registrations/admins'
  get 'registrations/users'

end

app/controllers/confirmedschedules_controller.rb
class ConfirmedschedulesController < ApplicationController
  layout 'registration'

def index
  @sdate_all = Sdate.all
  @schedule_all = Schedule.all

  date_today
end

def new
  @sdate_all = Sdate.all
  @schedule_all = Schedule.all
  date_next_today
end

private

def date_today
  @now = Date.today
  @wday_jan = ["月","火","水","木","金","土","日"]
  @this_year = @now.year
  @this_month = @now.month
  
  
  @first_day = @now.beginning_of_month
  @last_day = (@first_day + (7-@first_day.wday))
  @week_period = (@first_day..@last_day)

  @last_day2 = (@last_day + (7-@last_day.wday))
  @week_period2 = ((@last_day+1)..@last_day2)

  @last_day3 = (@last_day2 + (7-@last_day2.wday))
  @week_period3 = ((@last_day2+1)..@last_day3)

  @last_day4 = (@last_day3 + (7-@last_day3.wday))
  @week_period4 = ((@last_day3+1)..@last_day4)

  @last_day5 = (@last_day4 + (7-@last_day4.wday))
  @week_period5 = ((@last_day4+1)..@last_day5)

  @last_day6 = (@last_day5 + (7-@last_day5.wday))
  @week_period6 = ((@last_day5+1)..@last_day6)

end

def date_next_today
  @now = Date.today
  @wday_jan = ["月","火","水","木","金","土","日"]
  @this_year = @now.year
  @this_month = @now.month

  @next_month = @now.next_month.month
  
  @first_day = @now.end_of_month + 1
  @last_day = (@first_day + (7-@first_day.wday))
  @week_period = (@first_day..@last_day)

  @last_day2 = (@last_day + (7-@last_day.wday))
  @week_period2 = ((@last_day+1)..@last_day2)

  @last_day3 = (@last_day2 + (7-@last_day2.wday))
  @week_period3 = ((@last_day2+1)..@last_day3)

  @last_day4 = (@last_day3 + (7-@last_day3.wday))
  @week_period4 = ((@last_day3+1)..@last_day4)

  @last_day5 = (@last_day4 + (7-@last_day4.wday))
  @week_period5 = ((@last_day4+1)..@last_day5)

  @last_day6 = (@last_day5 + (7-@last_day5.wday))
  @week_period6 = ((@last_day5+1)..@last_day6)

  end

end

app/views/confirmedschedules/index.html.erb
<div class="schedule_title">
  <h1>Schedule Board</h1>
</div>


<div class="schedlues_wrapper">
  <div class="new_schedule_wrapper">
    <div class="date_today">
      <%= @this_year %>年<%= @this_month %>月
      <div class="date_next">
        <%= link_to "#{@this_month+1}月へ", new_confirmedschedule_path, method: :get %>
      </div>
    </div>



    <table border="1" id="schedule_table">
      <thead>
        <tr class="sdate_name">
          <th>月</th>
          <th>火</th>
          <th>水</th>
          <th>木</th>
          <th>金</th>
          <th><span id="sat">土</span></th>
          <th><span id="sun">日</span></th>
        </tr>
      </thead>
      <tbody>

        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period.each do |period| %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button class="schedule-button"></button>
              <div class="display-schedule"><%= schedule.subject %></div>
            </div>
            <div class="specify-schedule">
              <%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %><br>

              <%# confrimテーブルからcheckがtrueで、schedule_idが日付ごとのschedule_idと一致する複数行のuser_idたちを@usersに代入%>
              <% @users = Confirm.where(check: 1, schedule_id: schedule.id).pluck(:user_id) %>
              <%# 取得したユーザーidらの数を@lengthに代入%>
              <% @length = @users.length %>
              <%# ユーザーの数だけ繰り返す。nは0~@lengthが順番に実行される %>
              <% @length.times do |n| %>
              <%= User.find(@users[n]).last_name %>&nbsp;&nbsp;
              <%= User.find(@users[n]).first_name %><br>
              <% end %>

            </div>
            <% end %>
            <% end %>

            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>

        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period2.each do |period| %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button class="schedule-button"></button>
              <div class="display-schedule"><%= schedule.subject %></div>
            </div>
            <div class="specify-schedule"><%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %>

              <%# confrimテーブルからcheckがtrueで、schedule_idが日付ごとのschedule_idと一致する複数行のuser_idたちを@usersに代入%>
              <% @users = Confirm.where(check: 1, schedule_id: schedule.id).pluck(:user_id) %>
              <%# 取得したユーザーidらの数を@lengthに代入%>
              <% @length = @users.length %>
              <%# ユーザーの数だけ繰り返す。nは0~@lengthが順番に実行される %>
              <% @length.times do |n| %>
              <%= User.find(@users[n]).last_name %>&nbsp;&nbsp;
              <%= User.find(@users[n]).first_name %><br>
              <% end %>

            </div>
            <% end %>
            <% end %>

            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>

        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period3.each do |period| %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button class="schedule-button"></button>
              <div class="display-schedule"><%= schedule.subject %></div>
            </div>
            <div class="specify-schedule"><%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %>

              <%# confrimテーブルからcheckがtrueで、schedule_idが日付ごとのschedule_idと一致する複数行のuser_idたちを@usersに代入%>
              <% @users = Confirm.where(check: 1, schedule_id: schedule.id).pluck(:user_id) %>
              <%# 取得したユーザーidらの数を@lengthに代入%>
              <% @length = @users.length %>
              <%# ユーザーの数だけ繰り返す。nは0~@lengthが順番に実行される %>
              <% @length.times do |n| %>
              <%= User.find(@users[n]).last_name %>&nbsp;&nbsp;
              <%= User.find(@users[n]).first_name %><br>
              <% end %>

            </div>
            <% end %>
            <% end %>

            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>

        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period4.each do |period| %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button class="schedule-button"></button>
              <div class="display-schedule"><%= schedule.subject %></div>
            </div>
            <div class="specify-schedule"><%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %>

              <%# confrimテーブルからcheckがtrueで、schedule_idが日付ごとのschedule_idと一致する複数行のuser_idたちを@usersに代入%>
              <% @users = Confirm.where(check: 1, schedule_id: schedule.id).pluck(:user_id) %>
              <%# 取得したユーザーidらの数を@lengthに代入%>
              <% @length = @users.length %>
              <%# ユーザーの数だけ繰り返す。nは0~@lengthが順番に実行される %>
              <% @length.times do |n| %>
              <%= User.find(@users[n]).last_name %>&nbsp;&nbsp;
              <%= User.find(@users[n]).first_name %><br>
              <% end %>

            </div>
            <% end %>
            <% end %>

            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>

        <% if (@last_day4 + 1).month == @this_month %>
        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period5.each do |period| %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button class="schedule-button"></button>
              <div class="display-schedule"><%= schedule.subject %></div>
            </div>
            <div class="specify-schedule"><%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %>

              <%# confrimテーブルからcheckがtrueで、schedule_idが日付ごとのschedule_idと一致する複数行のuser_idたちを@usersに代入%>
              <% @users = Confirm.where(check: 1, schedule_id: schedule.id).pluck(:user_id) %>
              <%# 取得したユーザーidらの数を@lengthに代入%>
              <% @length = @users.length %>
              <%# ユーザーの数だけ繰り返す。nは0~@lengthが順番に実行される %>
              <% @length.times do |n| %>
              <%= User.find(@users[n]).last_name %>&nbsp;&nbsp;
              <%= User.find(@users[n]).first_name %><br>
              <% end %>

            </div>
            <% end %>
            <% end %>

            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>
        <% end %>

        <% if (@last_day5 + 1).month == @this_month %>
        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period6.each do |period| %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button class="schedule-button"></button>
              <div class="display-schedule"><%= schedule.subject %></div>
            </div>
            <div class="specify-schedule"><%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %>

              <%# confrimテーブルからcheckがtrueで、schedule_idが日付ごとのschedule_idと一致する複数行のuser_idたちを@usersに代入%>
              <% @users = Confirm.where(check: 1, schedule_id: schedule.id).pluck(:user_id) %>
              <%# 取得したユーザーidらの数を@lengthに代入%>
              <% @length = @users.length %>
              <%# ユーザーの数だけ繰り返す。nは0~@lengthが順番に実行される %>
              <% @length.times do |n| %>
              <%= User.find(@users[n]).last_name %>&nbsp;&nbsp;
              <%= User.find(@users[n]).first_name %><br>
              <% end %>

            </div>
            <% end %>
            <% end %>

            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>
        <% end %>

      </tbody>
    </table>
  </div>


</div>
<%= render "shared/schedule_footer"%>

app/views/confirmedschedules/new.html.erb
<div class="schedule_title">
  <h1>Schedule Board</h1>
</div>


<div class="schedlues_wrapper">
  <div class="new_schedule_wrapper">
    <div class="date_today">
      <%= @this_year %>年<%= @next_month%>月
      <div class="date_next">
        <%= link_to "#{@next_month - 1}月へ",confirmedschedules_path, method: :get %>
      </div>
    </div>



    <table border="1" id="schedule_table">
      <thead>
        <tr class="sdate_name">
          <th>月</th>
          <th>火</th>
          <th>水</th>
          <th>木</th>
          <th>金</th>
          <th><span id="sat">土</span></th>
          <th><span id="sun">日</span></th>
        </tr>
      </thead>
      <tbody>

        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period.each do |period| %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button class="schedule-button"></button>
              <div class="display-schedule"><%= schedule.subject %></div>
            </div>
            <div class="specify-schedule"><%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %>

              <%# confrimテーブルからcheckがtrueで、schedule_idが日付ごとのschedule_idと一致する複数行のuser_idたちを@usersに代入%>
              <% @users = Confirm.where(check: 1, schedule_id: schedule.id).pluck(:user_id) %>
              <%# 取得したユーザーidらの数を@lengthに代入%>
              <% @length = @users.length %>
              <%# ユーザーの数だけ繰り返す。nは0~@lengthが順番に実行される %>
              <% @length.times do |n| %>
              <%= User.find(@users[n]).last_name %>&nbsp;&nbsp;
              <%= User.find(@users[n]).first_name %><br>
              <% end %>

            </div>
            <% end %>
            <% end %>
            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>

        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period2.each do |period| %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button class="schedule-button"></button>
              <div class="display-schedule"><%= schedule.subject %></div>
            </div>
            <div class="specify-schedule"><%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %>

              <%# confrimテーブルからcheckがtrueで、schedule_idが日付ごとのschedule_idと一致する複数行のuser_idたちを@usersに代入%>
              <% @users = Confirm.where(check: 1, schedule_id: schedule.id).pluck(:user_id) %>
              <%# 取得したユーザーidらの数を@lengthに代入%>
              <% @length = @users.length %>
              <%# ユーザーの数だけ繰り返す。nは0~@lengthが順番に実行される %>
              <% @length.times do |n| %>
              <%= User.find(@users[n]).last_name %>&nbsp;&nbsp;
              <%= User.find(@users[n]).first_name %><br>
              <% end %>

            </div>
            <% end %>
            <% end %>

            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>

        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period3.each do |period| %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button class="schedule-button"></button>
              <div class="display-schedule"><%= schedule.subject %></div>
            </div>
            <div class="specify-schedule"><%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %>

              <%# confrimテーブルからcheckがtrueで、schedule_idが日付ごとのschedule_idと一致する複数行のuser_idたちを@usersに代入%>
              <% @users = Confirm.where(check: 1, schedule_id: schedule.id).pluck(:user_id) %>
              <%# 取得したユーザーidらの数を@lengthに代入%>
              <% @length = @users.length %>
              <%# ユーザーの数だけ繰り返す。nは0~@lengthが順番に実行される %>
              <% @length.times do |n| %>
              <%= User.find(@users[n]).last_name %>&nbsp;&nbsp;
              <%= User.find(@users[n]).first_name %><br>
              <% end %>

            </div>
            <% end %>
            <% end %>

            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>

        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period4.each do |period| %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button class="schedule-button"></button>
              <div class="display-schedule"><%= schedule.subject %></div>
            </div>
            <div class="specify-schedule"><%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %>

              <%# confrimテーブルからcheckがtrueで、schedule_idが日付ごとのschedule_idと一致する複数行のuser_idたちを@usersに代入%>
              <% @users = Confirm.where(check: 1, schedule_id: schedule.id).pluck(:user_id) %>
              <%# 取得したユーザーidらの数を@lengthに代入%>
              <% @length = @users.length %>
              <%# ユーザーの数だけ繰り返す。nは0~@lengthが順番に実行される %>
              <% @length.times do |n| %>
              <%= User.find(@users[n]).last_name %>&nbsp;&nbsp;
              <%= User.find(@users[n]).first_name %><br>
              <% end %>

            </div>
            <% end %>
            <% end %>

            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>

        <% if (@last_day4 + 1).month == @next_month %>
        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period5.each do |period| %>
            <% if period.month == @next_month %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button class="schedule-button"></button>
              <div class="display-schedule"><%= schedule.subject %></div>
            </div>
            <div class="specify-schedule"><%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %>

              <%# confrimテーブルからcheckがtrueで、schedule_idが日付ごとのschedule_idと一致する複数行のuser_idたちを@usersに代入%>
              <% @users = Confirm.where(check: 1, schedule_id: schedule.id).pluck(:user_id) %>
              <%# 取得したユーザーidらの数を@lengthに代入%>
              <% @length = @users.length %>
              <%# ユーザーの数だけ繰り返す。nは0~@lengthが順番に実行される %>
              <% @length.times do |n| %>
              <%= User.find(@users[n]).last_name %>&nbsp;&nbsp;
              <%= User.find(@users[n]).first_name %><br>
              <% end %>

            </div>
            <% end %>
            <% end %>

            <% end %>
            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>
        <% end %>

        <% if (@last_day5 + 1).month == @next_month %>
        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period6.each do |period| %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button class="schedule-button"></button>
              <div class="display-schedule"><%= schedule.subject %></div>
            </div>
            <div class="specify-schedule"><%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %>

              <%# confrimテーブルからcheckがtrueで、schedule_idが日付ごとのschedule_idと一致する複数行のuser_idたちを@usersに代入%>
              <% @users = Confirm.where(check: 1, schedule_id: schedule.id).pluck(:user_id) %>
              <%# 取得したユーザーidらの数を@lengthに代入%>
              <% @length = @users.length %>
              <%# ユーザーの数だけ繰り返す。nは0~@lengthが順番に実行される %>
              <% @length.times do |n| %>
              <%= User.find(@users[n]).last_name %>&nbsp;&nbsp;
              <%= User.find(@users[n]).first_name %><br>
              <% end %>

            </div>
            <% end %>
            <% end %>

            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>
        <% end %>

      </tbody>
    </table>
  </div>


</div>
<%= render "shared/schedule_footer"%>