config/routes.rb
Rails.application.routes.draw do
  root to: "boards#index" 
  resources :sdates
  resources :boards
  resources :rooms, only: [:new, :create, :destroy] do
    resources :messages, only: [:index, :create, :destroy]
    # member do
    #   post '/', to: 'rooms#add', as: 'add'
    #   get '/messages/', to: 'messages#index', as: 'message'
    # end
  end
  resources :adminrooms, only: [:new, :create, :destroy] do
    resources :adminmessages, only: [:index, :create, :destroy]
  # get 'rooms/:target_id', to: 'rooms#new', as: 'new_room' 
  # get 'rooms/:target_id/messages/', to 'messages#index'
  end

  resources :schedules do
    resources :checks, only: [:create,:update]
    member do
      get 'preview'
      post '/users/:user_id', to: 'confirms#switch'
      patch '/users/:user_id', to: 'confirms#switch'
      get 'next_preview'
      post '/next_users/:user_id', to: 'confirms#next_switch'
      patch '/next_users/:user_id', to: 'confirms#next_switch'
    end
  end

  resources :nextschedules
  resources :confirmedschedules
 
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  get 'registrations/admins'
  get 'registrations/users'

end

app/views/shared/_admin_signin_footer.html.erb
<div class="user_signup_footer">
  <div class="footer">
    <div class="footer_text">
    Copyright 2021 <span id="T">T</span>eaching<span id="B">B</span>uddy
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer_text">
  Copyright 2021 <span id="T">T</span>eaching<span id="B">B</span>uddy
  </div>
</div>

app/views/shared/_header.html.erb
<div class="header_wrapper">
  <div class="header_grid">
    <div id="school_name">
      <%= link_to image_tag("TeachingBuddy_logo.png", class:"teaching_logo"), "/" %>
    </div>
    <div class="header_nav">
      <div class="head_nav">
        <%= link_to 'トップページ', "/" %>
      </div>
      <div class="head_nav">
        <%= link_to '授業一覧', schedules_path %>
      </div>
      <div class="head_nav">
        <%= link_to 'Message Board', "/" %>
      </div>
      <% if user_signed_in? %>
      <div class="head_nav">
        <%= link_to 'Sign Out' , destroy_user_session_path, method: :delete %>
      </div>
      <% else %>
      <div class="head_nav">
        <%= link_to 'ログイン', new_user_session_path %>
      </div>
      <% end %>
      <div class="head_nav">
        <%= link_to '新規登録', registrations_users_path %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_header_admin.html.erb
<div class="header_wrapper">
  <div class="header_grid">
     <div id="school_name">
       <%= link_to image_tag("TeachingBuddy_logo.png", class:"teaching_logo"), "/" %>
     </div>
     <div class="header_nav">
       <div class="head_nav">
        <%= link_to 'トップページ', "/" %>
       </div>
       <div class="head_nav">
        <%= link_to '授業一覧', schedules_path %>
       </div>
       <div class="head_nav">
         <%= link_to 'Message Board', boards_path %>
       </div>
       <div class="head_nav">
        <%= link_to 'ログイン', new_admin_session_path %>
       </div>
     </div>
  </div>
</div>

app/views/shared/_index_footer.html.erb
<div class="index_footer">
  <div class="footer_text">
  Copyright 2021 <span id="T">T</span>eaching<span id="B">B</span>uddy
  </div>
</div>

app/views/shared/_index_header.html.erb
<div class="header_wrapper">
  <div class="header_grid">
     <div id="school_name">
       <%= link_to image_tag("TeachingBuddy_logo.png", class:"teaching_logo"), "/" %>
     </div>
     <div class="header_nav">
       <div class="head_nav">
        <%= link_to 'トップページ', "/" %>
       </div>
       <div class="head_nav">
        <%= link_to '授業一覧', "/" %>
       </div>
       <div class="head_nav">
         <%= link_to 'Message Board', "/" %>
       </div>
       <div class="head_nav">
        <%= link_to 'ログイン', new_user_session_path %>
       </div>
       <div class="head_nav">
        <%= link_to '新規登録', registrations_users_path %>
       </div>
     </div>
  </div>
</div>

app/views/shared/_members.html.erb
<div class="members">
  &nbsp;&nbsp;Members
  <% if user_signed_in? %>
  <% @users.each do |user| %>
  <div class="member_avatar">
    <%# <%= link_to image_tag(user.avatar.variant(resize: '80x80'),target: "_new", class: 'member_image'),room_path(user.id), method: :get if user.avatar.attached? %>
    <%= link_to image_tag(user.avatar.variant(resize: '80x80'),class: 'member_image'),new_room_path(user.id) if user.avatar.attached? %>
    <%# <%= image_tag user.avatar.variant(resize: '80x80'), class: 'member_image' if user.avatar.attached?%>

  </div>

 
  <% end %>
   <div class="member_avatar">
    &nbsp;&nbsp;<%= link_to 'Adminとの会話',new_adminroom_path(current_user.id) %>
    <% @adminrooms.each do |adminroom| %>
    <%= link_to adminroom.id,  adminroom_adminmessages_path(adminroom.id) %>
    <% end%>
  </div>
  <%= paginate @users, param_name: 'users_page' %>
  
  <% end %>

  <% if admin_signed_in? %>
  <% @users.each do |user| %>
  <div class="member_avatar">
    <%# <%= link_to image_tag(user.avatar.variant(resize: '80x80'),target: "_new", class: 'member_image'),room_path(user.id), method: :get if user.avatar.attached? %>
    <%= link_to image_tag(user.avatar.variant(resize: '80x80'),class: 'member_image'),new_adminroom_path(user.id) if user.avatar.attached? %>
    <%# <%= image_tag user.avatar.variant(resize: '80x80'), class: 'member_image' if user.avatar.attached?%>

  </div>

  <% end %>
  <%= paginate @users, param_name: 'users_page' %>
  <% end %>
</div>

app/views/shared/_message.html.erb
<div class="message">
  <div class="upper-message">
    <div class="message-user">
      <!-- 投稿したユーザー名情報を出力する -->
      <%= message.user.name %>
    </div>
    <div class="message-date">
      <!-- 投稿した時刻を出力する -->
      <%=l message.created_at %>
    </div>
  </div>
  <div class="lower-message">
    <div class="message-content">
      <!-- 投稿したメッセージ内容を記述する -->
      <%= message.content %>
    </div>
    <%= image_tag message.image.variant(resize: '500x500'), class: 'message-image' if message.image.attached? %>
  </div>
</div>    

app/views/shared/_regi_footer.html.erb
<div class="regi_footer">
  <div class="regi_footer_text">
  Copyright 2021 <span id="T">T</span>eaching<span id="B">B</span>uddy
  </div>
</div>

app/views/shared/_registration_footer.html.erb
<div class="registration_footer">
<div class="footer">
  <div class="registration_footer_text">
  Copyright 2021 <span id="T">T</span>eaching<span id="B">B</span>uddy
  </div>
  </div>
</div>

app/views/shared/_schedule_footer.html.erb
<div class="schedule_footer">
  <div class="footer">
    <div class="footer_text">
    Copyright 2021 <span id="T">T</span>eaching<span id="B">B</span>uddy
    </div>
  </div>
</div>

app/views/shared/_user_signin_footer.html.erb
<div class="regi_footer">
  <div class="footer">
  <div class="regi_footer_text">
  Copyright 2021 <span id="T">T</span>eaching<span id="B">B</span>uddy
  </div>
  </div>
</div>

app/views/shared/_user_signup_footer.html.erb
<div class="user_signup_footer">
  <div class="footer">
    <div class="footer_text">
    Copyright 2021 <span id="T">T</span>eaching<span id="B">B</span>uddy
    </div>
  </div>
</div>