config/routes.rb
Rails.application.routes.draw do
  root to: "boards#index" 
  resources :sdates
  resources :boards
  resources :rooms, only: [:new, :create, :destroy] do
    resources :messages, only: [:index, :create, :destroy]
    # member do
    #   post '/', to: 'rooms#add', as: 'add'
    #   get '/messages/', to: 'messages#index', as: 'message'
    # end
  end
  resources :adminrooms, only: [:new, :create, :destroy] do
    resources :adminmessages, only: [:index, :create, :destroy]
  # get 'rooms/:target_id', to: 'rooms#new', as: 'new_room' 
  # get 'rooms/:target_id/messages/', to 'messages#index'
  end

  resources :schedules do
    resources :checks, only: [:create,:update]
    member do
      get 'preview'
      post '/users/:user_id', to: 'confirms#switch'
      patch '/users/:user_id', to: 'confirms#switch'
      get 'next_preview'
      post '/next_users/:user_id', to: 'confirms#next_switch'
      patch '/next_users/:user_id', to: 'confirms#next_switch'
    end
  end

  resources :nextschedules
  resources :confirmedschedules
 
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  get 'registrations/admins'
  get 'registrations/users'

end

app/controllers/nextschedules_controller.rb
class NextschedulesController < ApplicationController
  layout 'registration'
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]
  before_action :set_check, only: [:show]

  def index
    users = User.where.not(id: current_user)
    @users = users.page(params[:users_page]).per(6)
    @sdate_all = Sdate.all
    @schedule_all = Schedule.all
    @checks_all = Check.where(user_id: current_user.id, check: 1).page(params[:page]).per(3) if user_signed_in?

    date_next_today
  end

  def new
    @sdate_schedule = SdateSchedule.new
    @sdate_all = Sdate.all
    @schedule_all = Schedule.all
  
    date_next_today
  end

  def show
    @check = Check.new
    @checks = @set_schedule.checks.includes(:user_name)
    @sdate = Sdate.all
    get_check_schedule_user
  end

  def update
    @set_schedule.update(edit_schedule_params)
    redirect_to new_nextschedule_path
  end

  def create
    @sdate_schedule = SdateSchedule.new(schedule_params)
    @sdate_schedule.save
    redirect_to new_nextschedule_path
  end

  def destroy
    @set_schedule.destroy
    redirect_to new_nextschedule_path
  end

  private

def get_check_schedule_user
  @get_checked_schedule_users = Check.where(schedule_id: params[:id], check: 1).pluck(:user_id)
end

def schedule_params
  params.require(:sdate_schedule).permit(:subject, :start_time, :end_time, :sdate)
end

def edit_schedule_params
  params.require(:schedule).permit(:subject, :start_time, :end_time)
end

#@set_checkが:idパラメーターを渡すか、空の容器なのかによって@set_checkの値を分岐させる。
def set_check
  #showの段階ではparams[:id]はshcedule_id値。現在のユーザーidがcheckテーブルのuser_idと同じであれば更新処理のためのテーブル情報を渡す。
    if current_user.id == Check.where(schedule_id: params[:id], user_id: current_user.id).pluck(:user_id)[0]
      @set_check = Check.find_by(params[:id])
  #現在のユーザーidがcheckテーブルに存在しなければ、新規エントリとして空の容器を用意。
    else
      @set_check = Check.new
    end
end

def set_schedule
  @set_schedule = Schedule.find(params[:id])
end

def date_next_today
  @now = Date.today
  @wday_jan = ["月","火","水","木","金","土","日"]
  @this_year = @now.year
  @this_month = @now.month

  @next_month = @now.next_month.month
  
  @first_day = @now.end_of_month + 1
  @last_day = (@first_day + (7-@first_day.wday))
  @week_period = (@first_day..@last_day)

  @last_day2 = (@last_day + (7-@last_day.wday))
  @week_period2 = ((@last_day+1)..@last_day2)

  @last_day3 = (@last_day2 + (7-@last_day2.wday))
  @week_period3 = ((@last_day2+1)..@last_day3)

  @last_day4 = (@last_day3 + (7-@last_day3.wday))
  @week_period4 = ((@last_day3+1)..@last_day4)

  @last_day5 = (@last_day4 + (7-@last_day4.wday))
  @week_period5 = ((@last_day4+1)..@last_day5)

  @last_day6 = (@last_day5 + (7-@last_day5.wday))
  @week_period6 = ((@last_day5+1)..@last_day6)

  end

end

app/views/nextschedules/index.html.erb
<div class="schedule_title">
  <h1>Schedule Board</h1>
</div>

<% if user_signed_in? %>
<div>Checked Schedule</div>
<% @checks_all.each do |display_checked| %>
<%= display_checked.schedule.sdate.sdate %>&nbsp;&nbsp;
<%= display_checked.schedule.start_time.to_s(:time) %>〜
<%= display_checked.schedule.end_time.to_s(:time) %>
&nbsp;&nbsp;
<button class="schedule-button"></button>
<%= link_to display_checked.schedule.subject, schedule_path(display_checked.schedule.id), target: "_new",class: "display-schedule",method: :get %>
<br>
<% end %>
<%=paginate @checks_all%>
<% end %>

<div class="schedlues_wrapper">
  <div class="new_schedule_wrapper">
    <div class="date_today">
      <% if @this_year == Time.current.next_month.year %><%= @this_year %><% else %><%= (@this_year + 1) %><% end %>年<%= @next_month %>月
      <div class="date_previous">
        <%= link_to "#{@this_month}月へ", schedules_path, method: :get %>
      </div>
    </div>

    <table border="1" id="schedule_table">
      <thead>
        <tr class="sdate_name">
          <th>月</th>
          <th>火</th>
          <th>水</th>
          <th>木</th>
          <th>金</th>
          <th><span id="sat">土</span></th>
          <th><span id="sun">日</span></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period.each do |period| %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button class="schedule-button"></button>
              <% if user_signed_in? %>
              <%= link_to schedule.subject, nextschedule_path(schedule.id), target: "_new",class: "display-schedule",method: :get %>
              <% else %>
              <%= link_to schedule.subject, next_preview_schedule_path(schedule.id), target: "_new",class: "display-schedule",method: :get %>
              <% end %>
            </div>
            <div class="specify-schedule"><%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %>
            </div>
            <% end %>
            <% end %>
            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>

        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period2.each do |period| %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button class="schedule-button"></button>
              <% if user_signed_in? %>
              <%= link_to schedule.subject, nextschedule_path(schedule.id), target: "_new",class: "display-schedule",method: :get %>
              <% else %>
              <%= link_to schedule.subject, next_preview_schedule_path(schedule.id), target: "_new",class: "display-schedule",method: :get %>
              <% end %>
            </div>
            <div class="specify-schedule"><%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %>
            </div>
            <% end %>
            <% end %>

            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>

        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period3.each do |period| %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button class="schedule-button"></button>
              <% if user_signed_in? %>
              <%= link_to schedule.subject, nextschedule_path(schedule.id), target: "_new",class: "display-schedule",method: :get %>
              <% else %>
              <%= link_to schedule.subject, next_preview_schedule_path(schedule.id), target: "_new",class: "display-schedule",method: :get %>
              <% end %>
            </div>
            <div class="specify-schedule"><%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %>
            </div>
            <% end %>
            <% end %>

            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>

        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period4.each do |period| %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button class="schedule-button"></button>
              <% if user_signed_in? %>
              <%= link_to schedule.subject, nextschedule_path(schedule.id), target: "_new",class: "display-schedule",method: :get %>
              <% else %>
              <%= link_to schedule.subject, next_preview_schedule_path(schedule.id), target: "_new",class: "display-schedule",method: :get %>
              <% end %>
            </div>
            <div class="specify-schedule"><%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %>
            </div>
            <% end %>
            <% end %>

            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>

        <% if (@last_day4 + 1).month == @next_month %>
        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period5.each do |period| %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button class="schedule-button"></button>
              <% if user_signed_in? %>
              <%= link_to schedule.subject, nextschedule_path(schedule.id), target: "_new",class: "display-schedule",method: :get %>
              <% else %>
              <%= link_to schedule.subject, next_preview_schedule_path(schedule.id), target: "_new",class: "display-schedule",method: :get %>
              <% end %>
            </div>
            <div class="specify-schedule"><%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %>
            </div>
            <% end %>
            <% end %>

            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>
        <% end %>


        <% if (@last_day5 + 1).month == @next_month %>
        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period6.each do |period| %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button class="schedule-button"></button>
              <% if user_signed_in? %>
              <%= link_to schedule.subject, nextschedule_path(schedule.id), target: "_new",class: "display-schedule",method: :get %>
              <% else %>
              <%= link_to schedule.subject, next_preview_schedule_path(schedule.id), target: "_new",class: "display-schedule",method: :get %>
              <% end %>
            </div>
            <div class="specify-schedule"><%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %>
            </div>
            <% end %>
            <% end %>

            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>
        <% end %>

      </tbody>
    </table>
  </div>


</div>
<%= render "shared/schedule_footer"%>

app/views/nextschedules/new.html.erb
<div class="schedule_title">
  <h1>授業新規登録</h1>
</div>

<div class="schedlues_wrapper">
  <div class="new_schedule_wrapper">
    <div class="date_today schedule">
      <% if @this_year == Time.current.next_month.year %><%= @this_year %><% else %><%= (@this_year + 1) %><% end %>年<%= @next_month %>月
      <div class="date_previous">
        <%= link_to "#{@this_month}月へ戻る", new_schedule_path, method: :get %>
      </div>
    </div>


    <table border="1" id="schedule_table">
      <thead>
        <tr class="sdate_name">
          <th>月</th>
          <th>火</th>
          <th>水</th>
          <th>木</th>
          <th>金</th>
          <th><span id="sat">土</span></th>
          <th><span id="sun">日</span></th>
        </tr>
      </thead>

      <div class="form_wrapper">
        <%= form_with model: @sdate_schedule, url: nextschedules_path, class: 'schedule_form', local: true do |f| %>
        <div class="input-wrapper">
          <span
            class="input-subject">Subject</span><%= f.text_field :subject, class:"schedule-input text", placeholder:"講座名を入力してください", maxlength:"20", autofocus:"true" %>
        </div>
        <%= f.date_field :sdate, class:'schedule-input',id:"choose-date" %>
        <div class="input-wrapper">
          <div class="schedule-input-time">
            <span class="input-start">Start Time</span><span id="edit_start_time"><%= f.time_select :start_time%></span>
          </div>
        </div>
        <div class="input-wrapper">
          <div class="schedule-input-time">
            <span class="input-end">End Time</span><span id="edit_end_time"><%= f.time_select :end_time%></span>
          </div>
        </div>
        <%= f.submit "Submit" ,class:"schedule-input",id:"submit-btn"%>
        <% end %>
      </div>

      <tbody>
        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period.each do |period| %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button
                class="schedule-button"></button><%= link_to schedule.subject, edit_schedule_path(schedule.id), target: "_new",class: "display-schedule",method: :get %>
            </div>
            <div class="specify-schedule"><%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %>
            </div>
            <% end %>
            <% end %>
            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>

        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period2.each do |period| %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button
                class="schedule-button"></button><%= link_to schedule.subject, edit_schedule_path(schedule.id), target: "_new",class: "display-schedule",method: :get %>
            </div>
            <div class="specify-schedule"><%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %>
            </div>
            <% end %>
            <% end %>

            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>

        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period3.each do |period| %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button
                class="schedule-button"></button><%= link_to schedule.subject, edit_schedule_path(schedule.id), target: "_new",class: "display-schedule",method: :get %>
            </div>
            <div class="specify-schedule"><%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %>
            </div>
            <% end %>
            <% end %>

            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>

        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period4.each do |period| %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button
                class="schedule-button"></button><%= link_to schedule.subject, edit_schedule_path(schedule.id), target: "_new",class: "display-schedule",method: :get %>
            </div>
            <div class="specify-schedule"><%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %>
            </div>
            <% end %>
            <% end %>

            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>

        <% if (@last_day4 + 1).month == @next_month %>
        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period5.each do |period| %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button
                class="schedule-button"></button><%= link_to schedule.subject, edit_schedule_path(schedule.id), target: "_new",class: "display-schedule",method: :get %>
            </div>
            <div class="specify-schedule"><%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %>
            </div>
            <% end %>
            <% end %>

            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>
        <% end %>

        <% if (@last_day5 + 1).month == @next_month %>
        <tr>
          <% 7.times do |x| %>
          <td class="schedule-row">
            <% @week_period6.each do |period| %>
            <% if x == (period -1).wday %>
            <span id="period_date">
              <%= period.day %>日
            </span>

            <% @schedule_all.each do |schedule| %>
            <% if period == schedule.sdate.sdate %>
            <div class="display-schedule-wrapper"><button
                class="schedule-button"></button><%= link_to schedule.subject, edit_schedule_path(schedule.id), target: "_new",class: "display-schedule",method: :get %>
            </div>
            <div class="specify-schedule"><%= schedule.start_time.to_s(:time) %>〜<%= schedule.end_time.to_s(:time) %>
            </div>
            <% end %>
            <% end %>

            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>
        <% end %>

      </tbody>
    </table>
  </div>


</div>
<%= render "shared/schedule_footer"%>

app/views/nextschedules/show.html.erb
<div class="edit_title">
  <h1>Show Schedule</h1>
</div>

<div class="edit_form_wrapper">

  <div class="input-wrapper">
    <span class="input-subject">Subject</span><%= @set_schedule.subject %>
  </div>
  <span class="input-subject date">Date</span><%= @set_schedule.sdate.sdate %>
  <div class="input-wrapper">
    <div class="schedule-input-time">
      <span class="input-start">Start Time</span><span
        id="edit_start_time"><%= @set_schedule.start_time.to_s(:time) %></span>
    </div>
  </div>
  <div class="input-wrapper">
    <div class="schedule-input-time">
      <span class="input-end">End Time</span><span id="edit_end_time"><%= @set_schedule.end_time.to_s(:time) %></span>
    </div>
  </div>

  <%= form_with model: [@set_schedule, @set_check], class: 'schedule_form',local: true do |f| %>
  <div class="edit_delete_wrapper">
    <%= f.check_box :check, :as => :boolean,checked:true %>
    <%= f.submit "Entry" ,class:"schedule-input",id:"submit-btn"%>
  </div>
  <% end %>

</div>

<%= link_to '戻る' ,nextschedules_path,id:"back" %>

<div>Checked Teachers</div>
<% @get_checked_schedule_users.each do |checked_schedule_user| %>
<%= image_tag(User.find(checked_schedule_user).avatar.variant(resize: '30x30' ))%>
<%= User.find(checked_schedule_user).last_name %>
<%= User.find(checked_schedule_user).first_name %>&nbsp;&nbsp;先生<br>
<% end %>

<%# <%= Check.find(45).schedule.subject%>